name: Build Windows
on:
  workflow_dispatch:

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  HUSKY: 0

jobs:
  build-windows:
    name: Build Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.91.0"
          targets: ${{ matrix.target }}

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          key: "rust-shared-${{ matrix.os }}-${{ matrix.target }}"
          workspaces: |
            . -> target
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.13.1"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install and copy resources
        run: |
          pnpm i
          pnpm run prebuild ${{ format('{0}', matrix.target) }}
        shell: bash

      - name: Add Rust Target
        run: |
          rustup target add ${{ matrix.target }} --toolchain 1.91.0 || rustup target add ${{ matrix.target }}
          rustup target list --installed
        shell: bash

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0.6.1
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm
          args: --target ${{ matrix.target }}

      - name: Zip Installer
        run: |
          cd target/${{ matrix.target }}/release/bundle/nsis
          7z a -p123456 ClashVerge-Windows_Installer.zip *setup.exe
        shell: bash

      - name: Generate SHA256
        shell: pwsh
        run: |
          $dir = "target/${{ matrix.target }}/release/bundle/nsis"
          Get-ChildItem -Path $dir -Filter "*.zip" | ForEach-Object {
            $hash = (Get-FileHash -Path $_.FullName -Algorithm SHA256).Hash.ToLower()
            Set-Content -Path "$($_.FullName).sha256" -Value "$hash  $($_.Name)" -Encoding ascii
          }

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.target }}-installer
          path: target/${{ matrix.target }}/release/bundle/nsis/ClashVerge-Windows_Installer.zip*
